### ISSUE TITLE
爲啥DEBIAN目錄是大寫

### ISSUE THREAD

**Issue by mahiuchun** [zonyitoo/qYaH3C#1]
一般不是小寫debian的嗎？

**Comment by zonyitoo** [comment]
我看的文档是大写的DEBIAN哦，应该没问题的吧，可能大写小写都可以

**Comment by mahiuchun** [comment]
http://www.debian.org/doc/manuals/maint-guide/index.en.html
是小寫吧……

**Comment by zonyitoo** [comment]
刚刚改成了debian，然后dpkg就报错了，说找不到软件包的info文件

``` bash
dpkg-deb: error: 无法打开软件包的 info 文件 ./pkg/DEBIAN/control 进行读取: 没有那个文件或目录
```

我看[这篇](http://netkiller.github.com/zh-tw/debian/dpkg.html)打包的时候说的是用大写DEBIAN的（不是官方文档，直接Google的）
去Google官网下载Chrome的deb包(google-chrome-stable_current_amd64.deb)打开来看，依然是大写DEBIAN

**Comment by mahiuchun** [comment]
原來你是不通過source包，直接生成binary包……那個Debian官方文檔是通過source包再生成binary包的……

**Comment by zonyitoo** [comment]
啊哈，原来可以像Arch那样直接通过源码来打包！
